# Python
## Python provides linear algebra libraries and other packages containing vector functions.

In [10]:
import numpy as np
import pandas as pd

***

### (s) Using Python and numpy, implement a function mag(vec) to return the magnitude of a 2-dimensional vector.

In [11]:
def mag(vec): 
    return np.linalg.norm(vec)

In [13]:
mag([5, 3])

5.830951894845301

In [15]:
mag([2, 3])

3.605551275463989

***

### (t) Likewise, implement a unit(vec) function to return the unit vector of a 2-dimensional vector (as a numpy array).

In [16]:
def unit(vec):
    return (vec / np.linalg.norm(vec))

In [28]:
unit([3, 4])

array([0.6, 0.8])

In [21]:
unit([2.31, 4.41])

array([0.46400699, 0.88583154])

***

### (u) Rotating a 2D vector 90 degrees counter clockwise is done by swapping x and y, and negating the new x. Implement rot90(vec). It must return a new numpy array, that is a 90 degree rotation of the vec input.

In [98]:
def rot90(vec):
    return (vec[1], -(vec[0]))

In [101]:
rot90([2, 3])

(3, -2)

In [103]:
rot90([3, -2])

(-2, -3)

In [104]:
rot90([-2, -3])

(-3, 2)

In [105]:
rot90([-3, 2])

(2, 3)

***

### (v) 2 · ~a

In [82]:
def multiplyVec(vec, num):
    return ([vec[0]*num, vec[1]*num])

In [83]:
multiplyVec([2, 3], 2)

[4, 6]

***

### (w) ~a +~b  ~c

In [86]:
def addAndSubtract(vec1, vec2, vec3):
    return np.subtract(np.add(vec1, vec2), vec3)

In [85]:
np.subtract(np.add([3, 2], [8, 7]), [1, 5])

array([10,  4])

In [87]:
addAndSubtract([3, 2], [8, 7], [1, 5])

array([10,  4])

***

### (x) Use the online documentation to find out how to calculate the dot product of two vectors.

In [88]:
numpy.dot([1, 5], [2, 3])

17

***

### (y) Using numpy, find ~a · ~a. Compare with mag(a)*mag(a). What is the difference?

In [89]:
numpy.dot([3, 2], [3, 2])

13

In [90]:
mag([3, 2])*mag([3, 2])

12.999999999999998

***

### (z) Using numpy, find ~a ·~b.

In [91]:
numpy.dot([3, 2], [8, 7])

38

***

### (æ) Using your rot90 function, find the dot product of a and its rotation.
#### (That is, given a~r = rot90(a), find ~a · a~r)

In [100]:
numpy.dot([3, 2], rot90([3, 2]))

0